### ISSUE TITLE
`dendrite-config.yaml` should be a secret until there's proper secret support

### ISSUE THREAD

**Issue by anthr76** [S7evinK/dendrite-helm#4]
I'm looking to finally deploy dendrite. Im curious what do you think of making the `dendrite-config.yaml` a secret until https://github.com/matrix-org/dendrite/issues/1958 is implemented.

**Comment by S7evinK** [comment]
Yea, sounds like a good idea. Somehow have forgotten about it.

**Comment by S7evinK** [comment]
I've moved the configuration to secrets in 2c5c7e98df21c for now.
